### PR TITLE
Add table of contents for easier navigation

### PR DESCRIPTION
**Pull request by weblancaster**
Add table of contents for easier navigation.

After read some of the content one day I came back days later and wanted to just jump to the section I was looking for.

### CODE REVIEW

**Comment by leebyron** [comment]
It would be better if the auto-generated TOC was just easier to navigate, which would be a change to https://github.com/leebyron/spec-md

**Comment by weblancaster** [comment]
Sorry @leebyron but I did not understand what you mean by that.. are you suggesting that spec-md auto generate navigation based on the md? or I got wrong.

**Comment by leebyron** [comment]
Yes. spec-md currently already generates a table of contents, so any improvements to it should be made there 



—

**Comment by leebyron** [comment]
Sorry for the delayed response here (holidays).

The built spec http://facebook.github.io/graphql/ already includes a table of contents, so I believe this diff would create a second redundant one which we want to avoid.

**Comment by leebyron** [comment]
The TOC is automatically generated by [spec-md](https://github.com/leebyron/spec-md/) so any improvements to the table of contents should be applied to that tool.

**Pull request closed without merging**
