### PR TITLE
Allow union type begining pipe

### PR DESCRIPTION
**Pull request by alexandrebodin**
Moved the PR onto this branch 
#320

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@robzhu @IvanGoncharov I update the PR here.

**Comment by leebyron** [comment]
Also, please don't forget to update the language grammar appendix

**Comment by alexandrebodin** [comment]
screen shot 2017-06-14 at 20 36 44

**Comment by leebyron** [comment]
Thanks! As I expected it's not rendering correctly. Notice other optional tokens have an <sub>opt</sub> subtext after them. This appears to require the literal character `?`.

**Comment by leebyron** [comment]
Do you think this form is weird or challenging to read? (open to advice)

```
UnionMembers :
  - LeadingPipe? NamedType
  - UnionMembers | NamedType

LeadingPipe: |
```

Otherwise a change to spec-md will be required as well

**Comment by alexandrebodin** [comment]
@leebyron I'm already working on a PR on `spec-md`I think it will be a lot more readable to have <sub>opt</sub>

**Comment by leebyron** [comment]
I've merged this into the RFC in #90 🥇

**Pull request closed without merging**
